/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sanctum/csrf-cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Issue CSRF cookie (Laravel Sanctum) */
        get: operations["csrfCookie"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Destroy the session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session user (bootstraps the app) */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/internship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current student's placement */
        get: operations["getMyInternship"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/journal/weeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List journal weeks for the current student */
        get: operations["listMyWeeks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/journal/weeks/{weekNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Week detail (daily logs + weekly draft/snapshot + capabilities) */
        get: operations["getMyWeek"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/journal/weeks/{weekNumber}/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Autosave one daily log (per-field, debounced, serialized) */
        put: operations["updateDailyEntry"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/journal/weeks/{weekNumber}/weekly-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Autosave the weekly draft (<=5000 chars, serialized per field) */
        put: operations["updateWeeklyDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/journal/weeks/{weekNumber}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomic submit/resubmit transition (latest text + version) */
        post: operations["submitWeek"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/supervisor/interns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company-scoped intern queue */
        get: operations["listSupervisorInterns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/supervisor/interns/{studentId}/weeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weeks for one in-scope intern */
        get: operations["listSupervisorInternWeeks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/supervisor/interns/{studentId}/weeks/{weekNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Submitted week detail for company review */
        get: operations["getSupervisorWeek"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/supervisor/interns/{studentId}/weeks/{weekNumber}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomic company review (approve | request-changes) */
        post: operations["supervisorReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mentor/mentees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assigned mentee queue */
        get: operations["listMentees"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mentor/mentees/{studentId}/weeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mentee weeks ready for mentor review (post company approval) */
        get: operations["listMenteeWeeks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mentor/mentees/{studentId}/weeks/{weekNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mentee week detail for mentor review */
        get: operations["getMenteeWeek"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mentor/mentees/{studentId}/weeks/{weekNumber}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomic mentor review (approve | request-changes restarts company) */
        post: operations["mentorReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** @default about:blank */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** @description Machine-readable code, e.g. UNAUTHENTICATED, FORBIDDEN, NOT_FOUND, VERSION_CONFLICT, STALE_VERSION, VALIDATION_FAILED, RATE_LIMITED, TRANSITION_CONFLICT, INTERNAL. */
            code: string;
            requestId: string;
            errors?: {
                [key: string]: string[];
            };
        };
        SessionUser: {
            id: string;
            name: string;
            email: string;
            role: components["schemas"]["UserRole"];
            avatar?: string;
            capabilities: components["schemas"]["Capabilities"];
        };
        /** @enum {string} */
        UserRole: "student" | "supervisor" | "university_mentor";
        /** @description Server-authoritative UI enablement. The client must not trust local role checks alone. */
        Capabilities: {
            canEdit: boolean;
            canSubmit: boolean;
            canReview: boolean;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        Internship: {
            id: string;
            studentId: string;
            companyId: string;
            universityName: string;
            programmeName: string;
            programmeTimeZone: string;
            companyName: string;
            position: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
        };
        WeekSummary: {
            weekNumber: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            status: components["schemas"]["JournalStatus"];
            /** @description Opaque version echoed as ETag; send back via If-Match. */
            version: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            submittedAt?: string;
            companyStatus?: components["schemas"]["ReviewStatus"];
            mentorStatus?: string | null;
            capabilities: components["schemas"]["Capabilities"];
        };
        WeekList: {
            data: components["schemas"]["WeekSummary"][];
            meta: components["schemas"]["PageMeta"];
        };
        WeekDetail: {
            weekNumber: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            status: components["schemas"]["JournalStatus"];
            version: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            submittedAt?: string;
            dailyEntries: components["schemas"]["DailyEntry"][];
            weeklyDraft: string;
            /** Format: date-time */
            weeklyDraftUpdatedAt?: string;
            submittedBody?: string;
            review?: components["schemas"]["Review"];
            mentorReview?: components["schemas"]["Review"];
            capabilities: components["schemas"]["Capabilities"];
        };
        /** @enum {string} */
        JournalStatus: "not_started" | "draft" | "submitted";
        /** @enum {string} */
        ReviewStatus: "pending" | "approved" | "changes_requested";
        Review: {
            status: components["schemas"]["ReviewStatus"];
            feedback?: string;
            reviewedBy?: string;
            /** Format: date-time */
            reviewedAt?: string;
        };
        DailyEntry: {
            /** Format: date */
            date: string;
            body: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        DailyUpdateRequest: {
            /** Format: date */
            date: string;
            body: string;
        };
        DailyUpdateResponse: {
            /** Format: date */
            date: string;
            body: string;
            /** Format: date-time */
            updatedAt?: string;
            version: string;
        };
        WeeklyDraftRequest: {
            draft: string;
        };
        WeeklyDraftResponse: {
            draft: string;
            /** Format: date-time */
            updatedAt?: string;
            version: string;
        };
        /** @description Submit carries the latest editor text plus the last-seen version so stale writes are rejected (412), never silently overwritten. */
        SubmitRequest: {
            draft: string;
            version: string;
        };
        ReviewRequest: {
            /** @enum {string} */
            decision: "approve" | "request_changes";
            /** @description Required when decision is request_changes. */
            feedback?: string;
        };
        InternSummary: {
            studentId: string;
            name: string;
            email: string;
            avatar: string;
            companyName: string;
            capabilities: components["schemas"]["Capabilities"];
        };
        InternList: {
            data: components["schemas"]["InternSummary"][];
            meta: components["schemas"]["PageMeta"];
        };
        PageMeta: {
            page: number;
            perPage: number;
            total: number;
        };
    };
    responses: {
        /** @description Missing/expired session. Client preserves drafts and prompts re-auth. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Out-of-scope resource (wrong company / unassigned mentee). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No placement/journal for this identity. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description State transition not allowed (409) — client keeps prior UI. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Stale version (412) — fetch server copy, show compare-then-retry. */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Validation failure (422), e.g. empty/over-limit weekly draft. */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Too many requests (429). */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Page: number;
        PerPage: number;
        WeekNumber: number;
        StudentId: string;
        /** @description Optimistic concurrency precondition (opaque version/ETag from the last GET). */
        IfMatch: string;
        /** @description Client-generated UUID v4; retries reuse the key so double-clicks apply once. */
        IdempotencyKey: string;
        /** @description Required for atomic transitions (submit/review). */
        IdempotencyKeyRequired: string;
    };
    requestBodies: never;
    headers: {
        /** @description Opaque resource version for If-Match. */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    csrfCookie: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF cookie set */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session user with capabilities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMyInternship: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Placement plus derived lifecycle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Internship"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listMyWeeks: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated weeks */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getMyWeek: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weekNumber: components["parameters"]["WeekNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Week detail */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateDailyEntry: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optimistic concurrency precondition (opaque version/ETag from the last GET). */
                "If-Match"?: components["parameters"]["IfMatch"];
                /** @description Client-generated UUID v4; retries reuse the key so double-clicks apply once. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                weekNumber: components["parameters"]["WeekNumber"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyUpdateRequest"];
            };
        };
        responses: {
            /** @description Saved daily log with new version */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyUpdateResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            422: components["responses"]["Unprocessable"];
        };
    };
    updateWeeklyDraft: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optimistic concurrency precondition (opaque version/ETag from the last GET). */
                "If-Match"?: components["parameters"]["IfMatch"];
                /** @description Client-generated UUID v4; retries reuse the key so double-clicks apply once. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                weekNumber: components["parameters"]["WeekNumber"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklyDraftRequest"];
            };
        };
        responses: {
            /** @description Saved draft with new version */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyDraftResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            422: components["responses"]["Unprocessable"];
        };
    };
    submitWeek: {
        parameters: {
            query?: never;
            header: {
                /** @description Optimistic concurrency precondition (opaque version/ETag from the last GET). */
                "If-Match"?: components["parameters"]["IfMatch"];
                /** @description Required for atomic transitions (submit/review). */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRequest"];
            };
        };
        responses: {
            /** @description Submitted week */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listSupervisorInterns: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated interns in the supervisor company */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listSupervisorInternWeeks: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated weeks (submitted snapshot only) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getSupervisorWeek: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentId"];
                weekNumber: components["parameters"]["WeekNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Week detail (submitted snapshot + dailies + capabilities) */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    supervisorReview: {
        parameters: {
            query?: never;
            header: {
                /** @description Optimistic concurrency precondition (opaque version/ETag from the last GET). */
                "If-Match"?: components["parameters"]["IfMatch"];
                /** @description Required for atomic transitions (submit/review). */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path: {
                studentId: components["parameters"]["StudentId"];
                weekNumber: components["parameters"]["WeekNumber"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Reviewed week */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listMentees: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated assigned mentees */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listMenteeWeeks: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated weeks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getMenteeWeek: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentId"];
                weekNumber: components["parameters"]["WeekNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Week detail (submitted snapshot + dailies + capabilities) */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    mentorReview: {
        parameters: {
            query?: never;
            header: {
                /** @description Optimistic concurrency precondition (opaque version/ETag from the last GET). */
                "If-Match"?: components["parameters"]["IfMatch"];
                /** @description Required for atomic transitions (submit/review). */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path: {
                studentId: components["parameters"]["StudentId"];
                weekNumber: components["parameters"]["WeekNumber"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Reviewed week */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            422: components["responses"]["Unprocessable"];
        };
    };
}
